[package]
name = "ipwall"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
description = "Download IP blocklists and add them to your iptables setup"

[dependencies]
anyhow = "1.0.57"
attohttpc = { version = "0.19.1", default-features = false, features = ["compress", "tls-rustls"] }
chrono = { version = "0.4.19", default-features = false, features = ["clock", "serde", "std"] }
clap = { version = "3.2.1", features = ["derive"] }
directories = "4.0.1"
duct = "0.13.5"
ipnetwork = { version = "0.19.0", default-features = false }
rand = "0.8.5"
serde = { version = "1.0.137", features = ["derive"] }
toml = "0.5.9"
which = "4.2.5"

[profile.release]
lto = true
strip = true
