[package]
name = "ipwall"
version = "0.1.1"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
description = "Download IP blocklists and add them to your iptables setup"

[dependencies]
anyhow = "1.0.66"
attohttpc = { version = "0.23.1", default-features = false, features = ["compress", "tls-rustls"] }
chrono = { version = "0.4.22", default-features = false, features = ["clock", "serde", "std"] }
clap = { version = "4.0.18", features = ["derive"] }
directories = "4.0.1"
duct = "0.13.5"
ipnetwork = { version = "0.20.0", default-features = false }
rand = "0.8.5"
serde = { version = "1.0.147", features = ["derive"] }
toml = "0.5.9"
which = "4.3.0"

[profile.release]
lto = true
strip = true
