
[licenses]
allow = [
    "MPL-2.0",
    "OpenSSL",
]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["GPL-3.0"], name = "ipwall" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
	{ name = "bitflags", version = "1" },
	{ name = "rustls-webpki", version = "0.100" },
]
